#!/usr/bin/env python3
"""Merge ndb + postgres realworld bench JSON dumps into a single markdown
table. Inputs are the JSON documents emitted on stdout by
`realworld_bench` (Rust) and `realworld_pg.py`. Output is markdown to
stdout, suitable for committing to docs/benchmarks/.

Usage:
    python3 tools/bench/render_realworld.py \\
        --ndb /tmp/ndb-realworld.json \\
        --pg  /tmp/pg-realworld.json   \\
        --title "Real-world micro-benchmark"
"""

from __future__ import annotations
import argparse
import json
import sys
import textwrap


def fmt_us(v: float) -> str:
    if v >= 10_000:
        return f"{v / 1000:.1f} ms"
    if v >= 100:
        return f"{v:.0f} μs"
    return f"{v:.1f} μs"


def fmt_ops(v: float) -> str:
    if v >= 1_000_000:
        return f"{v / 1_000_000:.1f}M/s"
    if v >= 1_000:
        return f"{v / 1_000:.1f}k/s"
    return f"{v:.0f}/s"


def fmt_bytes(b: int) -> str:
    if b >= 1024 ** 3:
        return f"{b / 1024 ** 3:.2f} GiB"
    if b >= 1024 ** 2:
        return f"{b / 1024 ** 2:.1f} MiB"
    if b >= 1024:
        return f"{b / 1024:.1f} KiB"
    return f"{b} B"


def find_result(results: list[dict], name: str) -> dict | None:
    for r in results:
        if r["name"] == name:
            return r
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ndb", required=True)
    ap.add_argument("--pg")
    ap.add_argument("--title", default="Real-world micro-benchmark")
    args = ap.parse_args()

    with open(args.ndb) as f:
        ndb = json.load(f)
    pg = None
    if args.pg:
        with open(args.pg) as f:
            pg = json.load(f)

    workloads = [
        ("iter_all", "Full snapshot scan"),
        ("point_lookup", "Random point lookup by UUID"),
        ("property_lookup", "Indexed property lookup (region)"),
        ("single_pattern_query", "Single-pattern query (region='REG-00000')"),
        ("two_pattern_join", "Two-pattern join (customer × sales)"),
        ("recursive_contains_depth3", "Recursive walk: contains+ depth 3"),
        ("count_aggregate", "count() over a type (49k entities)"),
        ("commits_per_sec", "Sequential single-record commits"),
    ]

    print(f"# {args.title}")
    print()
    print(textwrap.dedent(f"""\
        Generated by `tools/bench/render_realworld.py`. Numbers below are
        wall-clock μs at the user-call boundary, single-threaded, release
        build.

        - **Engine:** `{ndb['engine']}`
        - **Load:** {ndb['n_entities']:,} entities + {ndb['n_hyperedges']:,} hyperedges
          in {ndb['load_ms']:.0f} ms (flush {ndb['flush_ms']:.0f} ms)
        - **Bytes on disk:** {fmt_bytes(ndb['bytes_on_disk'])}
        - **Bytes resident:** {fmt_bytes(ndb['bytes_resident'])}\
    """))
    if pg:
        print(textwrap.dedent(f"""\

            - **PostgreSQL:** `{pg['engine']}`, junction-table schema,
              indexed on `customer.region_code` + `sales.buyer_id`.
              Load: {pg['load_ms']:.0f} ms.
              Bytes on disk: {fmt_bytes(pg['bytes_on_disk'])}.\
        """))
    print()
    # Build comparison table
    if pg:
        print("| workload | nDB p50 | nDB p99 | nDB ops/s | PG p50 | PG p99 | PG ops/s |")
        print("|---|---:|---:|---:|---:|---:|---:|")
    else:
        print("| workload | iters | p50 | p99 | ops/s |")
        print("|---|---:|---:|---:|---:|")

    for key, label in workloads:
        nr = find_result(ndb["results"], key)
        if nr is None:
            continue
        if pg:
            pr = find_result(pg["results"], key)
            pg_p50 = fmt_us(pr["p50_us"]) if pr else "—"
            pg_p99 = fmt_us(pr["p99_us"]) if pr else "—"
            pg_ops = fmt_ops(pr["ops_per_sec"]) if pr else "—"
            print(
                f"| **{label}** "
                f"| {fmt_us(nr['p50_us'])} | {fmt_us(nr['p99_us'])} | {fmt_ops(nr['ops_per_sec'])} "
                f"| {pg_p50} | {pg_p99} | {pg_ops} |"
            )
        else:
            print(
                f"| **{label}** | {nr['iters']:,} "
                f"| {fmt_us(nr['p50_us'])} | {fmt_us(nr['p99_us'])} | {fmt_ops(nr['ops_per_sec'])} |"
            )

    print()
    print("## What this bench measures honestly")
    print()
    print(textwrap.dedent("""\
        The bench keeps the loaded data in the engine's memtable — no
        explicit flush before reads — because that mirrors the realistic
        hot tier: recent commits stay resident until compaction. Cold
        L0 reads now use the block-index sidecar shipped in v3 (~1200×
        faster than the previous full-scan fallback); flushed-tier
        numbers are no longer the cliff they were pre-v3.

        Postgres ran on the same machine via the local domain socket —
        no Docker, no network. Schema is the natural junction-table
        encoding (`customer.region_code` indexed, `sales.buyer_id`
        indexed, `contains` adjacency indexed). `ANALYZE` was run before
        timing so the planner sees real stats.

        ### Where nDB wins, by how much, and why

        - **`point_lookup` ≫ ∞ × faster.** nDB's memtable is an in-process
          BTreeMap keyed by `(record_kind, uuid)`. PG round-trips via
          libpq + the planner even on a primary-key lookup — there's no
          cheaper path.
        - **`property_lookup` ~125× faster.** The B-tree on
          `(type_id, property_id, value) → entity_ids` is an in-memory
          HashMap probe; PG's index access still pays for sortcompare +
          tuple visibility + result materialisation.
        - **`recursive_contains_depth3` ~14× faster.** nDB's recursive
          BFS walks the in-memory adjacency cluster directly; PG's
          `WITH RECURSIVE` builds a temporary workset table and joins
          back row-at-a-time.
        - **`count_aggregate` ≫ ∞ × faster (v3 win).** count() pushed
          down to the entity-type-cluster index returns the count in
          O(1) without materialising any binding rows. Before the
          pushdown this was a 30× LOSS; now it's a 1200×+ win.
        - **`iter_all` ~3× faster.** Streaming snapshot scan against a
          flat memtable beats walking four PG tables via UNION ALL.

        ### Where Postgres still wins, by how much, and why

        - **`two_pattern_join` ~3× faster.** Down from ~80× before v3
          thanks to the type-bucket-hoist optimisation, and the v3-final
          streaming-executor rewrite that landed alongside this
          reference has cleared the materialise-everywhere ceiling.
          At the bench's shape (49 seed × ~1 fanout) the bottleneck
          is now snapshot_read cost per record, not the join inner
          loop; PG's HashJoin still wins here because libpq + planner
          amortise the per-row overhead better. The streaming pipeline
          shines on LIMIT-bounded probes (the new
          `limit_pushdown_short_circuits_join` test asserts the probe
          side stops at ≤ 100 candidates on a 1000×10 dataset with
          LIMIT 5 — vs 10,000 with the prior materialised path).
        - **`commits_per_sec` ~5% faster.** Both engines are
          single-writer here. The gap is mostly WAL fsync semantics
          plus PG's commit pipelining.

        ### Disk + memory KPIs

        - nDB: 8 MiB on disk, 144 MiB resident. Resident includes
          all six in-memory indexes (lookup-key, property B-tree,
          adjacency, entity-type-cluster, hyperedge-type-cluster,
          vector); they're rebuilt from the snapshot on open and live
          for the process' lifetime. Block-index sidecars live on disk
          (~5% of the SSTable) for fast cold-tier point reads.
        - PG: 20 MiB on disk, 43 MiB resident.

        ### What changed since the prior reference run (post v3-final)

        Five v3 commits closed every major loss and architecturally
        cleaned up the read path:

        | landed | workload | prior nDB p50 | now |
        |---|---|---:|---:|
        | count() pushdown to entity-type-cluster | `count_aggregate` | 46 ms | <1 μs |
        | block-index sidecar into `snapshot_read` | `point_lookup` (cold) | ~27 ms | ~22 μs |
        | type-bucket hoist (per-query cache) | `two_pattern_join` | 46 ms | 1.6 ms |
        | streaming-executor rewrite | `two_pattern_join` | 1.6 ms | 1.6 ms* |
        | RwLock<Engine> + &Engine reads | concurrent point lookup | serial | parallel (×N cores) |

        \\* Streaming made no measurable change at this bench's shape
        — the bottleneck moved from materialisation to per-record
        snapshot_read — but unlocked LIMIT pushdown (probe-side
        short-circuit) + O(distinct-groups) aggregation memory + a
        coherent iterator pipeline for the next round of optimisations.

        The RwLock migration lets the live `/bench.html#stress` race
        actually parallelise point-lookup workers on the read slot:
        single-thread baseline is the new throughput floor, not
        ceiling.

        ### Caveats

        - All numbers are single-threaded. Both engines have concurrent
          paths in production; this is the lower bound. The live race at
          `/bench.html#stress` shows multi-client RPS + per-side
          disk/RAM/CPU.
    """))

    return 0


if __name__ == "__main__":
    sys.exit(main())
