"""
Curated reaction list for chemistry_ndb.

Each REACTION names compounds; the SMILES + molecular formula for those
compounds is resolved at build time from PubChem (see build_seed.py).

Notation:
- reactants/products: list of [stoichiometry, compound_name]
- conditions: temperature_K, pressure_atm, ph, light, electric, ... (any free dict)
- gibbs_kjmol: ΔG° at standard conditions if known (-ve = exergonic)
- equilibrium_K: equilibrium constant at the conditions
- yield_pct: observed yield in a typical setup
- pathway: optional name; reactions sharing a pathway are linked into a T_PATHWAY hyperedge
- pathway_order: position in the pathway (1-based)
- citation: published source or textbook
"""
REACTIONS = [
    # ── Organic synthesis & classical name reactions ─────────────────
    {
        "name": "Aspirin synthesis",
        "reactants":  [[1, "salicylic acid"], [1, "acetic anhydride"]],
        "products":   [[1, "aspirin"], [1, "acetic acid"]],
        "catalyst":   "sulfuric acid",
        "solvent":    None,
        "conditions": {"temperature_K": 358, "pressure_atm": 1},
        "yield_pct":  74.0,
        "gibbs_kjmol": -32.0,
        "citation":   "Kolbe-Schmitt / Charles Gerhardt 1853",
        "family":     "Esterification",
    },
    {
        "name": "Diels-Alder: butadiene + ethylene",
        "reactants":  [[1, "1,3-butadiene"], [1, "ethylene"]],
        "products":   [[1, "cyclohexene"]],
        "catalyst":   None,
        "solvent":    None,
        "conditions": {"temperature_K": 473, "pressure_atm": 250},
        "yield_pct":  85.0,
        "gibbs_kjmol": -159.0,
        "citation":   "Diels & Alder 1928",
        "family":     "Cycloaddition",
    },
    {
        "name": "Friedel-Crafts acylation: benzene + acetyl chloride",
        "reactants":  [[1, "benzene"], [1, "acetyl chloride"]],
        "products":   [[1, "acetophenone"], [1, "hydrogen chloride"]],
        "catalyst":   "aluminum chloride",
        "solvent":    "dichloromethane",
        "conditions": {"temperature_K": 273, "pressure_atm": 1},
        "yield_pct":  85.0,
        "citation":   "Friedel & Crafts 1877",
        "family":     "Electrophilic aromatic substitution",
    },
    {
        "name": "Saponification of tristearin",
        "reactants":  [[1, "tristearin"], [3, "sodium hydroxide"]],
        "products":   [[1, "glycerol"], [3, "sodium stearate"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 373, "pressure_atm": 1},
        "yield_pct":  92.0,
        "citation":   "Industrial soap-making",
        "family":     "Hydrolysis",
    },
    {
        "name": "Fischer esterification: acetic acid + ethanol",
        "reactants":  [[1, "acetic acid"], [1, "ethanol"]],
        "products":   [[1, "ethyl acetate"], [1, "water"]],
        "catalyst":   "sulfuric acid",
        "solvent":    None,
        "conditions": {"temperature_K": 348, "pressure_atm": 1},
        "yield_pct":  67.0,
        "equilibrium_K": 4.0,
        "citation":   "Emil Fischer 1895",
        "family":     "Esterification",
    },
    {
        "name": "Suzuki-Miyaura coupling",
        "reactants":  [[1, "bromobenzene"], [1, "phenylboronic acid"]],
        "products":   [[1, "biphenyl"], [1, "boric acid"], [1, "potassium bromide"]],
        "catalyst":   "tetrakis(triphenylphosphine)palladium(0)",
        "solvent":    "tetrahydrofuran",
        "conditions": {"temperature_K": 343, "base": "potassium carbonate"},
        "yield_pct":  91.0,
        "citation":   "Miyaura & Suzuki 1979",
        "family":     "Cross-coupling",
    },
    {
        "name": "Grignard: methylmagnesium bromide + formaldehyde",
        "reactants":  [[1, "methylmagnesium bromide"], [1, "formaldehyde"]],
        "products":   [[1, "ethanol"], [1, "magnesium bromide hydroxide"]],
        "catalyst":   None,
        "solvent":    "diethyl ether",
        "conditions": {"temperature_K": 273, "atmosphere": "dry nitrogen"},
        "yield_pct":  75.0,
        "citation":   "Grignard 1900 (Nobel 1912)",
        "family":     "Organometallic addition",
    },
    {
        "name": "Wacker oxidation: ethylene to acetaldehyde",
        "reactants":  [[1, "ethylene"], [0.5, "oxygen"]],
        "products":   [[1, "acetaldehyde"]],
        "catalyst":   "palladium(II) chloride",
        "solvent":    "water",
        "conditions": {"temperature_K": 393, "pressure_atm": 3, "co_catalyst": "copper(II) chloride"},
        "yield_pct":  95.0,
        "citation":   "Smidt 1959 (Wacker-Chemie)",
        "family":     "Oxidation",
    },

    # ── Inorganic & industrial ───────────────────────────────────────
    {
        "name": "Haber-Bosch ammonia synthesis",
        "reactants":  [[3, "hydrogen"], [1, "nitrogen"]],
        "products":   [[2, "ammonia"]],
        "catalyst":   "iron",
        "solvent":    None,
        "conditions": {"temperature_K": 723, "pressure_atm": 200},
        "yield_pct":  15.0,
        "gibbs_kjmol": -33.0,
        "equilibrium_K": 6.8e5,
        "citation":   "Haber & Bosch 1909, Nobel 1918/1931",
        "family":     "Industrial inorganic",
    },
    {
        "name": "Contact process: sulfur dioxide oxidation",
        "reactants":  [[2, "sulfur dioxide"], [1, "oxygen"]],
        "products":   [[2, "sulfur trioxide"]],
        "catalyst":   "vanadium(V) oxide",
        "solvent":    None,
        "conditions": {"temperature_K": 723, "pressure_atm": 2},
        "yield_pct":  98.0,
        "gibbs_kjmol": -141.0,
        "citation":   "Phillips 1831 (industrial)",
        "family":     "Industrial inorganic",
    },
    {
        "name": "Methane combustion",
        "reactants":  [[1, "methane"], [2, "oxygen"]],
        "products":   [[1, "carbon dioxide"], [2, "water"]],
        "catalyst":   None,
        "solvent":    None,
        "conditions": {"temperature_K": 2200, "pressure_atm": 1, "ignition": "spark"},
        "yield_pct":  99.0,
        "gibbs_kjmol": -800.0,
        "citation":   "Standard combustion",
        "family":     "Combustion",
    },
    {
        "name": "Iron oxidation (rusting)",
        "reactants":  [[4, "iron"], [3, "oxygen"]],
        "products":   [[2, "iron(III) oxide"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 298, "humidity_pct": 80},
        "yield_pct":  60.0,
        "gibbs_kjmol": -742.0,
        "citation":   "Slow ambient oxidation",
        "family":     "Corrosion",
    },
    {
        "name": "Sodium chloride neutralisation",
        "reactants":  [[1, "hydrogen chloride"], [1, "sodium hydroxide"]],
        "products":   [[1, "sodium chloride"], [1, "water"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 298, "pressure_atm": 1, "ph": 7.0},
        "yield_pct":  100.0,
        "gibbs_kjmol": -56.0,
        "citation":   "Standard strong-strong neutralisation",
        "family":     "Acid-base",
    },
    {
        "name": "Sodium chloride formation",
        "reactants":  [[2, "sodium"], [1, "chlorine"]],
        "products":   [[2, "sodium chloride"]],
        "catalyst":   None,
        "solvent":    None,
        "conditions": {"temperature_K": 298, "pressure_atm": 1},
        "yield_pct":  100.0,
        "gibbs_kjmol": -769.0,
        "citation":   "Standard ionic bond formation",
        "family":     "Redox",
    },
    {
        "name": "Water electrolysis",
        "reactants":  [[2, "water"]],
        "products":   [[2, "hydrogen"], [1, "oxygen"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 298, "voltage_V": 1.23, "electric": True},
        "yield_pct":  95.0,
        "gibbs_kjmol": 237.0,
        "citation":   "Nicholson & Carlisle 1800",
        "family":     "Electrolysis",
    },
    {
        "name": "Calcium carbonate calcination",
        "reactants":  [[1, "calcium carbonate"]],
        "products":   [[1, "calcium oxide"], [1, "carbon dioxide"]],
        "catalyst":   None,
        "solvent":    None,
        "conditions": {"temperature_K": 1173, "pressure_atm": 1},
        "yield_pct":  99.0,
        "gibbs_kjmol": -57.0,
        "citation":   "Lime kiln industrial",
        "family":     "Thermal decomposition",
    },

    # ── Biochemistry: overall reactions ─────────────────────────────
    {
        "name": "Photosynthesis (overall, Calvin cycle summed)",
        "reactants":  [[6, "carbon dioxide"], [6, "water"]],
        "products":   [[1, "glucose"], [6, "oxygen"]],
        "catalyst":   "RuBisCO",
        "solvent":    "water",
        "conditions": {"temperature_K": 298, "ph": 8.0, "light_quanta": 48, "compartment": "chloroplast stroma"},
        "yield_pct":  8.0,
        "gibbs_kjmol": 2870.0,
        "citation":   "Bassham, Benson & Calvin 1950 (Nobel 1961)",
        "family":     "Photosynthesis",
    },
    {
        "name": "Cellular respiration (overall)",
        "reactants":  [[1, "glucose"], [6, "oxygen"]],
        "products":   [[6, "carbon dioxide"], [6, "water"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4, "compartment": "mitochondrion"},
        "yield_pct":  40.0,
        "gibbs_kjmol": -2870.0,
        "citation":   "Krebs 1937 (Nobel 1953)",
        "family":     "Catabolism",
    },

    # ── Glycolysis (10 sequential reactions, pathway = "Glycolysis") ──
    {
        "name": "Glycolysis step 1: hexokinase",
        "reactants":  [[1, "glucose"], [1, "adenosine triphosphate"]],
        "products":   [[1, "glucose 6-phosphate"], [1, "adenosine diphosphate"]],
        "catalyst":   "hexokinase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4, "compartment": "cytosol"},
        "gibbs_kjmol": -16.7,
        "citation":   "EC 2.7.1.1",
        "pathway":    "Glycolysis", "pathway_order": 1,
    },
    {
        "name": "Glycolysis step 2: phosphoglucose isomerase",
        "reactants":  [[1, "glucose 6-phosphate"]],
        "products":   [[1, "fructose 6-phosphate"]],
        "catalyst":   "phosphoglucose isomerase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 1.7,
        "citation":   "EC 5.3.1.9",
        "pathway":    "Glycolysis", "pathway_order": 2,
    },
    {
        "name": "Glycolysis step 3: phosphofructokinase-1",
        "reactants":  [[1, "fructose 6-phosphate"], [1, "adenosine triphosphate"]],
        "products":   [[1, "fructose 1,6-bisphosphate"], [1, "adenosine diphosphate"]],
        "catalyst":   "phosphofructokinase-1",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -14.2,
        "citation":   "EC 2.7.1.11 — committed step",
        "pathway":    "Glycolysis", "pathway_order": 3,
    },
    {
        "name": "Glycolysis step 4: aldolase",
        "reactants":  [[1, "fructose 1,6-bisphosphate"]],
        "products":   [[1, "dihydroxyacetone phosphate"], [1, "glyceraldehyde 3-phosphate"]],
        "catalyst":   "fructose-bisphosphate aldolase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 23.8,
        "citation":   "EC 4.1.2.13",
        "pathway":    "Glycolysis", "pathway_order": 4,
    },
    {
        "name": "Glycolysis step 5: triose phosphate isomerase",
        "reactants":  [[1, "dihydroxyacetone phosphate"]],
        "products":   [[1, "glyceraldehyde 3-phosphate"]],
        "catalyst":   "triose phosphate isomerase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 7.5,
        "citation":   "EC 5.3.1.1 — diffusion-limited enzyme",
        "pathway":    "Glycolysis", "pathway_order": 5,
    },
    {
        "name": "Glycolysis step 6: GAPDH",
        "reactants":  [[1, "glyceraldehyde 3-phosphate"], [1, "NAD+"], [1, "phosphate"]],
        "products":   [[1, "1,3-bisphosphoglycerate"], [1, "NADH"]],
        "catalyst":   "glyceraldehyde 3-phosphate dehydrogenase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 6.3,
        "citation":   "EC 1.2.1.12",
        "pathway":    "Glycolysis", "pathway_order": 6,
    },
    {
        "name": "Glycolysis step 7: phosphoglycerate kinase",
        "reactants":  [[1, "1,3-bisphosphoglycerate"], [1, "adenosine diphosphate"]],
        "products":   [[1, "3-phosphoglycerate"], [1, "adenosine triphosphate"]],
        "catalyst":   "phosphoglycerate kinase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -18.8,
        "citation":   "EC 2.7.2.3 — first ATP made",
        "pathway":    "Glycolysis", "pathway_order": 7,
    },
    {
        "name": "Glycolysis step 8: phosphoglycerate mutase",
        "reactants":  [[1, "3-phosphoglycerate"]],
        "products":   [[1, "2-phosphoglycerate"]],
        "catalyst":   "phosphoglycerate mutase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 4.4,
        "citation":   "EC 5.4.2.11",
        "pathway":    "Glycolysis", "pathway_order": 8,
    },
    {
        "name": "Glycolysis step 9: enolase",
        "reactants":  [[1, "2-phosphoglycerate"]],
        "products":   [[1, "phosphoenolpyruvate"], [1, "water"]],
        "catalyst":   "enolase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 7.5,
        "citation":   "EC 4.2.1.11",
        "pathway":    "Glycolysis", "pathway_order": 9,
    },
    {
        "name": "Glycolysis step 10: pyruvate kinase",
        "reactants":  [[1, "phosphoenolpyruvate"], [1, "adenosine diphosphate"]],
        "products":   [[1, "pyruvate"], [1, "adenosine triphosphate"]],
        "catalyst":   "pyruvate kinase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -31.7,
        "citation":   "EC 2.7.1.40 — second ATP made",
        "pathway":    "Glycolysis", "pathway_order": 10,
    },

    # ── Citric acid (Krebs) cycle — 8 reactions in a loop ─────────────
    {
        "name": "Krebs step 1: citrate synthase",
        "reactants":  [[1, "acetyl-CoA"], [1, "oxaloacetate"], [1, "water"]],
        "products":   [[1, "citrate"], [1, "coenzyme A"]],
        "catalyst":   "citrate synthase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4, "compartment": "mitochondrial matrix"},
        "gibbs_kjmol": -32.2,
        "citation":   "EC 2.3.3.1",
        "pathway":    "Krebs cycle", "pathway_order": 1,
    },
    {
        "name": "Krebs step 2: aconitase",
        "reactants":  [[1, "citrate"]],
        "products":   [[1, "isocitrate"]],
        "catalyst":   "aconitase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 13.3,
        "citation":   "EC 4.2.1.3",
        "pathway":    "Krebs cycle", "pathway_order": 2,
    },
    {
        "name": "Krebs step 3: isocitrate dehydrogenase",
        "reactants":  [[1, "isocitrate"], [1, "NAD+"]],
        "products":   [[1, "alpha-ketoglutarate"], [1, "carbon dioxide"], [1, "NADH"]],
        "catalyst":   "isocitrate dehydrogenase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -8.4,
        "citation":   "EC 1.1.1.41",
        "pathway":    "Krebs cycle", "pathway_order": 3,
    },
    {
        "name": "Krebs step 4: alpha-ketoglutarate dehydrogenase complex",
        "reactants":  [[1, "alpha-ketoglutarate"], [1, "NAD+"], [1, "coenzyme A"]],
        "products":   [[1, "succinyl-CoA"], [1, "carbon dioxide"], [1, "NADH"]],
        "catalyst":   "alpha-ketoglutarate dehydrogenase complex",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -33.5,
        "citation":   "EC 1.2.4.2",
        "pathway":    "Krebs cycle", "pathway_order": 4,
    },
    {
        "name": "Krebs step 5: succinyl-CoA synthetase",
        "reactants":  [[1, "succinyl-CoA"], [1, "GDP"], [1, "phosphate"]],
        "products":   [[1, "succinate"], [1, "GTP"], [1, "coenzyme A"]],
        "catalyst":   "succinyl-CoA synthetase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -2.9,
        "citation":   "EC 6.2.1.4 — substrate-level phosphorylation",
        "pathway":    "Krebs cycle", "pathway_order": 5,
    },
    {
        "name": "Krebs step 6: succinate dehydrogenase",
        "reactants":  [[1, "succinate"], [1, "FAD"]],
        "products":   [[1, "fumarate"], [1, "FADH2"]],
        "catalyst":   "succinate dehydrogenase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 0.0,
        "citation":   "EC 1.3.5.1 — complex II of ETC",
        "pathway":    "Krebs cycle", "pathway_order": 6,
    },
    {
        "name": "Krebs step 7: fumarase",
        "reactants":  [[1, "fumarate"], [1, "water"]],
        "products":   [[1, "malate"]],
        "catalyst":   "fumarase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": -3.8,
        "citation":   "EC 4.2.1.2",
        "pathway":    "Krebs cycle", "pathway_order": 7,
    },
    {
        "name": "Krebs step 8: malate dehydrogenase",
        "reactants":  [[1, "malate"], [1, "NAD+"]],
        "products":   [[1, "oxaloacetate"], [1, "NADH"]],
        "catalyst":   "malate dehydrogenase",
        "solvent":    "water",
        "conditions": {"temperature_K": 310, "ph": 7.4},
        "gibbs_kjmol": 29.7,
        "citation":   "EC 1.1.1.37 — regenerates oxaloacetate",
        "pathway":    "Krebs cycle", "pathway_order": 8,
    },

    # ── Polymerisation ─────────────────────────────────────────────
    {
        "name": "Ethylene polymerisation (Ziegler-Natta)",
        "reactants":  [[1000, "ethylene"]],
        "products":   [[1, "polyethylene"]],
        "catalyst":   "titanium tetrachloride",
        "solvent":    "hexane",
        "conditions": {"temperature_K": 343, "pressure_atm": 10, "co_catalyst": "triethylaluminum"},
        "yield_pct":  98.0,
        "citation":   "Ziegler & Natta 1953 (Nobel 1963)",
        "family":     "Coordination polymerisation",
    },
    {
        "name": "Nylon-6,6 condensation",
        "reactants":  [[1, "hexamethylenediamine"], [1, "adipic acid"]],
        "products":   [[1, "nylon-6,6 unit"], [2, "water"]],
        "catalyst":   None,
        "solvent":    None,
        "conditions": {"temperature_K": 553, "pressure_atm": 1},
        "yield_pct":  95.0,
        "citation":   "Carothers (DuPont) 1935",
        "family":     "Condensation polymerisation",
    },

    # ── Famous mechanistic landmarks ────────────────────────────────
    {
        "name": "Hofmann rearrangement: amide to amine",
        "reactants":  [[1, "acetamide"], [1, "bromine"], [4, "sodium hydroxide"]],
        "products":   [[1, "methylamine"], [1, "sodium carbonate"], [2, "sodium bromide"], [2, "water"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 313, "ph": 13},
        "yield_pct":  70.0,
        "citation":   "Hofmann 1881",
        "family":     "Rearrangement",
    },
    {
        "name": "Maillard reaction: amino acid + sugar (initial)",
        "reactants":  [[1, "glucose"], [1, "glycine"]],
        "products":   [[1, "fructosylamine"], [1, "water"]],
        "catalyst":   None,
        "solvent":    "water",
        "conditions": {"temperature_K": 423, "ph": 6.5},
        "yield_pct":  35.0,
        "citation":   "Maillard 1912",
        "family":     "Browning",
    },
    {
        "name": "Belousov-Zhabotinsky reaction (overall)",
        "reactants":  [[3, "malonic acid"], [4, "potassium bromate"], [1, "sulfuric acid"]],
        "products":   [[1, "bromomalonic acid"], [1, "carbon dioxide"], [1, "water"]],
        "catalyst":   "cerium(IV)",
        "solvent":    "water",
        "conditions": {"temperature_K": 298, "oscillating": True},
        "yield_pct":  50.0,
        "citation":   "Belousov 1958, Zhabotinsky 1964",
        "family":     "Oscillating",
    },
    {
        "name": "Wittig olefination",
        "reactants":  [[1, "methyltriphenylphosphonium bromide"], [1, "butyllithium"], [1, "benzaldehyde"]],
        "products":   [[1, "styrene"], [1, "triphenylphosphine oxide"], [1, "lithium bromide"]],
        "catalyst":   None,
        "solvent":    "tetrahydrofuran",
        "conditions": {"temperature_K": 273, "atmosphere": "dry nitrogen"},
        "yield_pct":  82.0,
        "citation":   "Wittig 1953 (Nobel 1979)",
        "family":     "Carbonyl olefination",
    },
    {
        "name": "Mannich reaction",
        "reactants":  [[1, "acetone"], [1, "formaldehyde"], [1, "dimethylamine"]],
        "products":   [[1, "1-(dimethylamino)-3-butanone"], [1, "water"]],
        "catalyst":   "hydrogen chloride",
        "solvent":    "water",
        "conditions": {"temperature_K": 333, "ph": 5.0},
        "yield_pct":  60.0,
        "citation":   "Mannich 1912",
        "family":     "Aminoalkylation",
    },
]

# Pathway membership (derived from `pathway` field in REACTIONS).
# Each pathway becomes a T_PATHWAY hyperedge whose roles are the
# constituent reactions in order.
PATHWAYS = ["Glycolysis", "Krebs cycle"]
